### ISSUE TITLE
Use Wordpress Categories instead of Tags

### ISSUE THREAD

**Issue by nohillside** [JenniferMack/Ulysses-post-to-WP#1]
Is there any way to use the second line (between the `:: ::`) for the categories of the blog instead for tags?

**Comment by JenniferMack** [comment]
Yes, but it be a new script. There’s no way to chose options when exporting from Ulysses. I’ll look into the changes needed then create a branch that does  categories. Give me a few days. Ok?

**Comment by nohillside** [comment]
No hurry at all :-) I tried to adapt it myself, but somehow couldn't make sense of the Wordpress API documentation. Not having any practical Ruby experience to speak of didn't help either...

**Comment by JenniferMack** [comment]
Ok, categories are working now. Instead of a new branch, I included both categories and tags in the code. It defaults to tags, so commenting that line and uncommenting the category line will enable categories.

181fcf80cc4d9d893af46fcc1375cc70e94ed3c7, lines 31-35

Let me know if this works for you.

**Comment by nohillside** [comment]
Great, works perfectly. Thanks for the update!
