### ISSUE TITLE
Can't access ~/bin

### ISSUE THREAD

**Issue by rickprice407** [JenniferMack/Ulysses-post-to-WP#7]
I'm running El Capitan and have run into a problem in that I can't access /bin.  So I parked wp-post.rb on my desktop.

I edited the automator script to show:

for f in "$@"
do
    ~/Users/MyMacName/Desktop/wp-post.rb "$f"
done 

When I run the script it asks if I want to post to wordpress, I say yes and I get a notification that I think is waiting for the result and then goes away.  Nothing published.  Also nothing in the export menu of Ulysses.

Thanks,

Rick Price

**Comment by JenniferMack** [comment]
You probably shouldn’t use `~` along with the full path. Try

`~/Desktop/wp-post.rb "$f”`

And if you’ve made your own `bin` folder at the root of your user folder, you should have write access to it.

But...

If you’re getting the message, that means the script is running. So working is better than not working. The problem is that you have to do the export from inside Ulysses. Running the script by clicking does exactly what you’re getting. Nothing. Because the script doesn’t talk to Ulysses. Ulysses has to talk to the script.

Follow the steps on the read me page, and use the Ulysses export function.
